### ISSUE TITLE
Midterm and Endterm question paper

### ISSUE THREAD

**Issue by anshitbansal21** [fenilgmehta/CS695-Assignment-1#1]
Hey! I could not reach out to you in any other way, could you please send me the midterm and endterm paper for this course..
reach out to me here - ab499@snu.edu.in

I have a paper and my prof is using same resources as yours.

Thank you

**Comment by fenilgmehta** [comment]
Hi @anshitbansal21,
I have replied at the given email ID. I hope you have received it.
Thanks

**Comment by anshitbansal21** [comment]
Thank you so much for your help!
